version: '3.8'

services:
  my-app:
    image: nginx # Una imagen ligera con herramientas básicas
    command: ["sh", "-c", "echo 'Contenedor iniciado. Esperando 60 segundos.' && sleep 60"] # Para mantener el contenedor vivo
    volumes:
      - ./:/app_data # Monta el directorio actual del repositorio en /app_data dentro del contenedor
      - my-named-volume:/persisted_data # Un volumen nombrado para probar persistencia

volumes:
  my-named-volume: null
